src/contents/config/main.xml, src/contents/ui/ConfigGeneral.qml, src/contents/ui/main.qml
The preferred source combobox shows `@multiplex` also when the saved preferred source is an other.
Fix #3
=> fix: preferred source combobox shows always @multiplex

src/contents/ui/main.qml
The controls size were fixed and did not fit the available height, causing the buttons to overflow when the panel was too small.
Fix #2
=> fix: responsive controls size in compact representation

src/contents/ui/PlayerDataSource.qml, src/contents/ui/main.qml
Fallback to default value when a property is not defined for the current datasource.
Fix #13
=> fix: handle missing datasource properties

src/contents/ui/PlayerDataSource.qml
This caused the datasource to connect to a source even when it wasn't available. As a result, when the source did become available, the connectSource function had no effect.
Fix #18
=> fix: sourceName comparison in PlayerDatasource lifecycle functions

src/contents/config/main.xml, src/contents/ui/ConfigGeneral.qml, src/contents/ui/ScrollingText.qml, src/contents/ui/main.qml
When song text overflows the max width:
- Always scroll (default, the only one available until now)
- Scroll only when the mouse is over the text.
- Always scroll except when the mouse is over the text.
Fix https://github.com/ccatterina/plasmusic-toolbar/issues/26, https://github.com/ccatterina/plasmusic-toolbar/issues/27
=> feat: add new scrolling options for song text overflow

src/contents/ui/Player.qml
The existance of mprisModel.currentPlayer was checked comparing it to undefined but currentPlayer can be also null.
=> fix: currentPlayer existance check

src/contents/ui/Player.qml, src/contents/ui/main.qml
- Search and set the current player also when the preferred source name changes and not only when a new source is added.
- Search among all the available sources to choose the player to set as the current one.
- Set Plasmoid.status on `player.onReadyChanged` event. Apparently calculating Plasmoid.status using `player.ready` variable not always works.
- Add debug log on events like current player change or player readyness change.
Fix #60
=> fix: Player sources handling improvements

src/contents/ui/main.qml
Sometimes the widget was visible also when there were no active players or the preferred source player is not active.
Apparently calculating Plasmoid.status using `player.ready` variable doesn't always work.
Fix #60
=> fix: widget visibile when there is no active player

src/metadata.json
The description field in the metadata seems to be used in its tooltip. So I think it's best to make it less verbose.
For reference, this is another plasmoid:
=> Less verbose plasmoid description

src/contents/ui/ScrollingText.qml
Song text behaviours `Scroll only on mouse over` and `Always scroll except on mouse over` were not working with touchpad due to the fact that the PointerDevice.TouchPad was not listed in the AcceptedDevices of the HoverHandler component.
=> fix: Enable song text hover behaviours for touchpad

src/contents/ui/Player.qml, src/contents/ui/TrackPositionSlider.qml
If the track was long more than ~30min the track position slider show wrong time labels and didn't change the track position correctly.
=> fix: Track position slider doesn't work properly with long track

src/contents/config/main.xml, src/contents/ui/ConfigGeneral.qml, src/contents/ui/PanelIcon.qml, src/contents/ui/main.qml
- round corner with album image
- add config option `albumCoverRadius`
known issue:
sometimes the Canvas does not repaint after the song is switched, needs to track this issue.
after applying the radius settings, Canvas does not update. (I'm a newer of kde widget development)
=> feat: radius with album image

src/contents/ui/main.qml
https://github.com/KDE/plasma-workspace/blob/master/applets/mediacontroller/package/contents/ui/main.qml#L136
=> fix: Use correct back/next icon

src/contents/ui/ScrollingText.qml
After player restart, the first song with text long enough to exceed the available space, started scrolling also if the selected scroll behaviour was "Scroll only on mouse over"
=> fix: text scroll on mouse over not working as expected

README.md
I updated the README file to include instructions for installing the widget using the Nix package manager and NixOS modules, as plasmusic-toolbar was finally [merged](https://github.com/NixOS/nixpkgs/pull/319671) into nixpkgs.
I am the currently maintainer of the package, but you can add yourself as a maintainer too, if you want to.
=> Add Nix package installation instructions

src/contents/config/main.xml, src/contents/ui/ConfigGeneral.qml, src/contents/ui/main.qml
Works only if the widget is used as a desktop applet.
Fix #122
=> feat: add an option to make the widget bg transparent (desktop)

src/contents/config/main.xml, src/contents/ui/ConfigGeneral.qml, src/contents/ui/Player.qml, src/contents/ui/main.qml
New UX/UI for preferred source configuration:
- New combobox to select player source from the currently active ones.
- New informational tooltips to explain how the source config works.
- The selected source is matched with Mpris source `identity` instead of source `desktopEntry`. This make the source match more reliable because some sources (e.g. chromium) haven't a `desktopEntry`.
Fix #1078
BREAKING CHANGE: Brake old source config, the preferred source must be reconfigured with the new UI.
=> feat!: improve preferred source config

src/contents/ui/PanelIcon.qml, src/contents/ui/main.qml
1. Wait for a short time (500ms) after the Image status change
2. If the image didn't load and fallback is enabled show the icon
3. If the image didn't load and fallback is disabled hide PanelIcon instead of leaving the empty space
closes: https://github.com/ccatterina/plasmusic-toolbar/issues/148
=> feat: fallback to panel icon if cover image doesn't load

src/contents/config/main.xml, src/contents/ui/ConfigGeneral.qml, src/contents/ui/PanelIcon.qml, src/contents/ui/ScrollingText.qml, src/contents/ui/main.qml
Depends on https://github.com/ccatterina/plasmusic-toolbar/pull/150
closes: https://github.com/ccatterina/plasmusic-toolbar/issues/120
=> feat: option to tint widget with cover image dominant color

src/contents/ui/config/Compact.qml
A contextual help button  to clarify that "Background" section requires Use album cover as icon" to be enabled.
=> improve: add contextual help for background color option

src/contents/config/main.xml, src/contents/ui/Compact.qml, src/contents/ui/Full.qml, src/contents/ui/Player.qml, src/contents/ui/components/ScrollingText.qml, src/contents/ui/components/SongAndArtistText.qml, src/contents/ui/config/Compact.qml, src/contents/ui/config/Full.qml, src/contents/ui/config/General.qml
It now has two new options
- show album title
- show album title below song title and artists
I also updated the logic for SongAndArtistsText.qml to make it easier to create logic for how to organize all of the text, depending on what options are selected in the configuration.
I also added html tags to bold and italicise the song title and album title, respectively. These each have their own option in the configuration as well.
(https://github.com/ccatterina/plasmusic-toolbar/issues/168)
=> Add an option to display album title and configure where it displays

src/contents/config/main.xml, src/contents/ui/components/SongAndArtistText.qml, src/contents/ui/config/General.qml, src/contents/ui/main.qml
This solves #143.
It keeps the toolbar widget always open, regardless of whether or not media is playing.
It also adds two new options:
- Show widget when no media playing (checkbox)
- Text displayed when no media playing (text field)
The second allows the customizable text mentioned in #143.
=> Make an option for the widget to be always visible

src/contents/ui/config/Compact.qml
1 is too small for my 20pt panel, 1.1 is just perfect. It doesn't look too out of place, so I think having a wider range of option will be better for everyone else as well
=> Increase max controls size
