- README.md
- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/ScrollingText.qml
- src/contents/ui/main.qml
> feat: text scrolling speed configuration

- src/contents/ui/ScrollingText.qml
- src/contents/ui/main.qml
> feat: smoother text scrolling animation

- src/contents/ui/main.qml
> fix: preserve album image aspect ratio

- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/main.qml
Hey I really like your applet, but I thought it was missing the option to separate the title and artist into two lines. I haven't really taken part in FOSS so far, so please excuse if this is not the standard way to do things. 
If you have any comments on this feature please let me know.
I would be happy to contribute to your applet.
Best Luke
> add option to separate title from artist into two lines

- src/contents/ui/main.qml
Plasmoid.status refactored for better clarity and efficiency.
> refactor: Improve handling of Plasmoid.status in main.qml

- src/contents/ui/Player.qml
- src/contents/ui/TrackPositionSlider.qml
- src/contents/ui/main.qml
Apparently seek function doesn't work with some players (e.g. yesplaymusic)
Possible solution for #63
> fix: set position instead of use seek function

- src/contents/ui/Player.qml
- src/contents/ui/main.qml
This reverts commit 0844cbc3d390a661121c01d62d17c97a758c0453.
This commit seems to make plasmashell crash when a preferred source is selected (#70)
> Revert "fix: Player sources handling improvements"

- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/PanelIcon.qml
- src/contents/ui/main.qml
> feat: radius with album image

- README.md
- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/main.qml
> feat: add ability to choose font style

- src/contents/ui/VolumeBar.qml
> Increase volume bar clickable area and make it draggable

- src/contents/ui/main.qml
> Limit minimum expanded representation size to content

- src/contents/ui/Player.qml
- src/contents/ui/main.qml
> Raise player on cover click and Ctrl+click from panel

- README.md
- Update installation instructions for plasma-manager, as extraWidgets were removed in nix-community/plasma-manager#263
- Add nix package badge
> docs: add nix package badge and update plasma-manager installation instructions

- src/contents/ui/Player.qml
- src/contents/ui/main.qml
> feat: Show title and artist in Tooltip

- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/ScrollingText.qml
- src/contents/ui/main.qml
Closes: https://github.com/ccatterina/plasmusic-toolbar/issues/45
> feat: Text scrolling: allow to disable and reset on pause

- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/MouseAreaWithWheelHandler.qml
- src/contents/ui/Player.qml
- src/contents/ui/VolumeBar.qml
- src/contents/ui/main.qml
Also go previous/next with back/forward mouse buttons
Allow to scroll the volume bar to adjust volume
Closes: #115
> feat: Mouse wheel click to play/pause and scroll to adjust volume

- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/PanelIcon.qml
- src/contents/ui/main.qml
> feat: fallback to selected icon when no album cover available

- src/contents/ui/ScrollingText.qml
- src/contents/ui/main.qml
> fix: same spacing for left/right side of text

- src/contents/config/main.xml
- src/contents/ui/main.qml
closes: https://github.com/ccatterina/plasmusic-toolbar/issues/147
> feat: vertical panel support

- src/contents/config/main.xml
- src/contents/ui/ConfigGeneral.qml
- src/contents/ui/main.qml
> feat: fill available space in the panel

- src/translate/nl.po
> Added Dutch translation
